SELECT E.ID, COALESCE(C.CHILD_COUNT, 0) CHILD_COUNT
FROM ECOLI_DATA E
LEFT JOIN (SELECT PARENT_ID, COUNT(*) CHILD_COUNT
      FROM ECOLI_DATA
      GROUP BY PARENT_ID) C ON E.ID = C.PARENT_ID
ORDER BY E.ID ASC