-- 코드를 입력하세요
SELECT r.FOOD_TYPE, r.REST_ID, r.REST_NAME, r.FAVORITES
FROM REST_INFO r
JOIN (
    SELECT MAX(FAVORITES) FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) s ON r.FAVORITES = s.FAVORITES
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC