-- 코드를 입력하세요
WITH MAX_FAVORITES AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT r.FOOD_TYPE, r.REST_ID, r.REST_NAME, r.FAVORITES
FROM REST_INFO r
JOIN MAX_FAVORITES m ON r.FOOD_TYPE = m.FOOD_TYPE AND r.FAVORITES = m.FAVORITES
GROUP BY r.FOOD_TYPE
ORDER BY r.FOOD_TYPE DESC