-- 코드를 입력하세요
SELECT I.REST_ID REST_ID,
       I.REST_NAME REST_NAME,
       I.FOOD_TYPE FOOD_TYPE,
       I.FAVORITES FAVORITES,
       I.ADDRESS ADDRESS,
       ROUND(A.SCORE_AVG, 2) SCORE
FROM REST_INFO I
JOIN (SELECT REST_ID,
             AVG(REVIEW_SCORE) SCORE_AVG
      FROM REST_REVIEW
      GROUP BY REST_ID) A ON I.REST_ID = A.REST_ID
WHERE ADDRESS LIKE '서울%'
ORDER BY SCORE_AVG DESC, FAVORITES DESC