WITH AVG_GRADE AS (
    SELECT EMP_NO,
           CASE WHEN AVG(SCORE) >= 96 THEN 'S'
                WHEN AVG(SCORE) >= 90 THEN 'A'
                WHEN AVG(SCORE) >= 80 THEN 'B'
                ELSE 'C'
                END AS GRADE
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT E.EMP_NO EMP_NO,
       E.EMP_NAME EMP_NAME,
       G.GRADE GRADE,
       CASE WHEN G.GRADE = 'S' THEN SAL * 0.2
            WHEN G.GRADE = 'A' THEN SAL * 0.15
            WHEN G.GRADE = 'B' THEN SAL * 0.1
            ELSE 0
            END AS BOUNS
FROM HR_EMPLOYEES E
JOIN AVG_GRADE G ON E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO
ORDER BY E.EMP_NO