-- 코드를 입력하세요
SELECT EXTRACT(HOUR FROM DATETIME) HOUR, COUNT(*) COUNT
FROM ANIMAL_OUTS
WHERE EXTRACT(HOUR FROM DATETIME) >= '9' AND EXTRACT(HOUR FROM DATETIME) <= 19
GROUP BY EXTRACT(HOUR FROM DATETIME)
ORDER BY HOUR