-- 코드를 입력하세요
SELECT M.MEMBER_NAME MEMBER_NAME,
       R.REVIEW_TEXT REVIEW_TEXT,
       DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID
JOIN (SELECT MEMBER_ID, COUNT(REVIEW_ID) REVIEW_COUNT
      FROM REST_REVIEW
      GROUP BY MEMBER_ID
      ORDER BY REVIEW_COUNT DESC
      LIMIT 1) S ON R.MEMBER_ID = S.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT