SELECT YEAR(O.DIFFERENTIATION_DATE) AS YEAR,
       S.MAX_SIZE - O.SIZE_OF_COLONY AS YEAR_DEV,
       O.ID
FROM ECOLI_DATA O
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
             MAX(SIZE_OF_COLONY) AS MAX_SIZE
      FROM ECOLI_DATA
      GROUP BY YEAR(DIFFERENTIATION_DATE)) S ON YEAR(O.DIFFERENTIATION_DATE) = S.YEAR
ORDER BY YEAR, YEAR_DEV