-- 코드를 입력하세요
WITH MAX_PRICE AS (
    SELECT CATEGORY, MAX(PRICE) PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY = '과자' OR CATEGORY = '국' OR CATEGORY = '김치' OR CATEGORY = '식용유'
    GROUP BY CATEGORY
)

SELECT F.CATEGORY, F.PRICE MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN MAX_PRICE M ON F.PRICE = M.PRICE AND F.CATEGORY = M.CATEGORY
GROUP BY F.CATEGORY
ORDER BY F.PRICE DESC